# Generated by Django 3.2 on 2021-04-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol', models.CharField(max_length=6)),
                ('pangkat', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pegawai',
            name='pangkat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pegawai.pangkat'),
        ),
    ]
