# Generated by Django 3.2 on 2021-04-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_auto_20210424_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangkat',
            name='pangkat',
            field=models.CharField(max_length=20),
        ),
    ]
